### obtener todos los characters
GET http://localhost:3000/api/tipoCursos


### obtener un character
GET http://localhost:3000/api/tipoCursos/a02b91bc-3769-4221-beb1-d7a3aeba7dad

### crear un nuevo character
POST http://localhost:3000/api/tipoCursos
Content-Type: application/json

{
  "nombre": "Javascript",
  "descripcion": "Pipipipipipipipi",
}

### modificar un character (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/tipoCursos/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
  "nombre": "Python",
  "descripcion": "Pupupupupupu",   
}

### modificar un character (PATCH - recurso parcial)
PATCH http://localhost:3000/api/tipoCursos/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
  "name": "Anakin Skywalker",
  "characterClass": "Fallen Jedi",
  "items": ["Lightsaber", "X-Wing"],
  "level": 12    
}

### borrar un character
DELETE http://localhost:3000/api/characters/a02b91bc-3769-4221-beb1-d7a3aeba7dad