###Obtener todas las aplicaciones
GET http://localhost:3000/api/appeals


###Obtener una aplicación
GET http://localhost:3000/api/appeals/689df8f44148ea580cc465f5


###Crear una aplicación - rápido
@createdAt = {{$datetime iso8601}}
POST http://localhost:3000/api/appeals
Content-Type: application/json

{
    "date": "{{createdAt}}",
    "text": "Quiero que me acepten la solicitud porfis",
    "student": "689dee4a65944b53fdb78ed9"
}


###Modificar una aplicación existente (PATCH)
PATCH http://localhost:3000/api/appeals/689df8f44148ea580cc465f5
Content-Type: application/json

{
    "state": "accepted"
}

###Borrar una aplicación
DELETE http://localhost:3000/api/appeals/689df8f44148ea580cc465f5